<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KeySwitch</AssemblyName>
    <Version>1.2.1</Version>
    <FileVersion>1.2.1.0</FileVersion>
    <Product>KeySwitch</Product>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../KeySwitch.Core/KeySwitch.Core.csproj" />
  </ItemGroup>
</Project>
